baseURL = 'https://maryzender.com/'
languageCode = 'en-us'
title = 'Maryzender Rodríguez-Melgarejo'

[params]
  description = "Research portfolio of Maryzender Rodríguez-Melgarejo. Systematics and evolution of high Andean and Neotropical rove beetles (Staphylinidae)"
  author = "Maryzender Rodríguez-Melgarejo"
  defaultImage= "/assets/mary.jpg"

[taxonomies]
  # Empty block disables default tag/category generation

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    name = "Publications"
    pageRef = "/publications/"
    weight = 20

  [[menus.main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 30

  [[menus.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 40

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIRECTS]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "REDIRECTS", "RSS"]
  section = ["HTML", "RSS", "JSON"]